[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[workspace]
resolver = "2"
members = [
    "blockchain_p",
    "guess_this",
    "brain_math",
    "minigrep",
    "mt_web_serv",
    "sha1",
    "webbest_socket",
    "number_regn",
    "proc_m",
    "playground", "bit_tor",
]
